# Não foi setado versão pois há aviso de configuração obsoleta
services:
  apache:
    image: httpd:latest
    container_name: my-apache-app
    ports:
    - '80:80'
    volumes:
    - ./website:/usr/local/apache2/htdocs
# Não foi setado rede pois em teste em outra máquina poderia haver diferença